NethServer/ns8-traefik

- README.md
- imageroot/actions/delete-route/20writeconfig
- imageroot/actions/set-route/20writeconfig
- imageroot/actions/set-route/validate-input.json
With the `strip_prefix` (boolean) option is possible to strip the
prefix of the requested path from the original request before sending
it to the downstream server.
> Strip the prefix path from the requests

- .github/workflows/test-module.yml
This workflow will be invoked after the `Publish images` workflow and
will execute the module's tests suite against the just created module
image. The workflow can be also executed manually.
> Add `test-module.yml` workflow

- README.md
- imageroot/actions/get-certificate/20readconfig
- imageroot/actions/get-certificate/validate-input.json
- imageroot/actions/get-certificate/validate-output.json
- imageroot/actions/list-certificates/20readconfig
- imageroot/actions/list-certificates/validate-output.json
- tests/20_traefik_certificates_api.robot
This PR will add two new APIs
- get-certificate`:  get the current status of a requested certificate
-  'list-certificates': get a list of the currently requested certificates
It Is also provided a new test suite for all the current get/set/list/delete certificates APIs
See the updated README for the full documentation.
> Add APIs to get the status of the requested certificates

- imageroot/actions/delete-certificate/20writeconfig
- imageroot/actions/delete-certificate/21waitsync
- imageroot/actions/delete-route/20writeconfig
- imageroot/actions/delete-route/21waitsync
- imageroot/actions/get-certificate/20readconfig
- imageroot/actions/get-route/20readconfig
- imageroot/actions/set-certificate/20writeconfig
- imageroot/actions/set-certificate/21waitsync
- imageroot/actions/set-route/20writeconfig
- imageroot/actions/set-route/21waitsync
- imageroot/pypkg/get_certificate.py
- imageroot/pypkg/get_route.py
- tests/10_traefik_routes_api.robot
- tests/20_traefik_certificates_api.robot
Calling an API on NS8 system, via `agent.run()` or `api-cli` cli, is supposed to beave synchronous and return the control to the called process only at the end of action execution.
With the `traefik`'s APIs the synchronous behavior is not respected because when writing the configuration to Redis it may take some time before that `traefik` read the new configuration and fully apply it. 
This can lead to undefined behavior in that time frame, like a partially configured route that returns `404` or `500` when the caller application expects instead the route to be ready.
This PR tries to correct the above problem with these steps:
* Make the read APIs aware that the system can be partially configured and handle that cases.
* Use the Redis pipelining mechanism to wire the configuration, to …
> Make `delete-*` and `set-*` APIs synchronous

- imageroot/bin/export-certificate
According to docs, the rule is "use past tense inside the name".
> Fix certificate-updated event name

- README.md
- imageroot/actions/create-module/30grants
In this PR
- Define the new role
- Fix routeadm
- Update README
The `certadm` role is necessary to modules like ns8-mail that provide non-HTTP based services: the `set-route` API does not fit them.
> New API role "certadm"

- README.md
- imageroot/actions/list-certificates/20readconfig
- imageroot/actions/list-certificates/validate-input.json
- imageroot/actions/list-certificates/validate-output.json
- imageroot/actions/list-routes/20readconfig
- imageroot/actions/list-routes/validate-input.json
- imageroot/actions/list-routes/validate-output.json
- tests/10_traefik_routes_api.robot
- tests/20_traefik_certificates_api.robot
If set to `true` the routes/certificates list will be expanded with all details.
The UI can use this new option to retrieve the full routes/certificates list and display it as a table or check if the path was already used, without run N tasks to get the all properties of the routes.
> list-(certificates|routes): add expand_list option

- imageroot/bin/export-certificate
According to our docs, "the parameter should contain minimal required
info about the event".
Passing the Redis key is a lightweight alternative to the
whole certificate+key data: clients can use it to retrieve the data, if
needed.
> Reduce Redis event payload size

- README.md
- imageroot/actions/get-route/validate-output.json
- imageroot/actions/set-route/20writeconfig
- imageroot/actions/set-route/validate-input.json
- imageroot/pypkg/get_route.py
- tests/10_traefik_routes_api.robot
Using `user_created` flag is possible to mark a route as manually created by a user, in this way the UI can avoid a system route begin deleted or modified by mistake.
> (get|set)-route: add user_created flag

- README.md
- imageroot/actions/set-route/20writeconfig
Invert the priority of the `host` and the `host` + `path` routes, in
this way the more specific route will win over the more generic one.
> set-route: change routes priority

- imageroot/update-module.d/20restart
https://trello.com/c/vhdX28Wl/336-core-p0-traefik-does-not-restart-after-update
> Fix restart

- imageroot/actions/create-module/10expandconfig
The mail parameter is not mandatory, but if it contains an invalid domain, the certificate challenge will fail with an error like:
```
Error creating new account :: contact email "root@localhost.localdomain" has invalid domain :
Domain name does not end with a valid public suffix (TLD)"
```
See https://trello.com/c/R5XZnhDv/332-core-p3-handle-bad-fqdns
> expandconfig: remove default LE_MAIL

- imageroot/actions/create-module/05set_env
- imageroot/actions/create-module/10expandconfig
- imageroot/actions/create-module/50create
following https://trello.com/c/jBkc6Qwt/365-core-p1-agent-set-env-deprecation
Remove the deprecated set-env
Sync the agent Redis */environment key on every action run, no matter for the exit code
> Remove obsolete bash set-env

- README.md
- imageroot/actions/create-module/50create
- imageroot/actions/set-route/20writeconfig
- imageroot/actions/upload-certificate/20decode_upload
- imageroot/actions/upload-certificate/21validate_certificates
- imageroot/actions/upload-certificate/22save_certificates
- imageroot/actions/upload-certificate/validate-input.json
- imageroot/systemd/user/traefik.service
Added action allowing upload of custom certificate to Traefik
[Trello Ref](https://trello.com/c/UooTDELP/315-core-p1-upload-tls-certificate)
> Upload custom certificate

- imageroot/actions/delete-certificate/20writeconfig
- imageroot/actions/get-certificate/20readconfig
- imageroot/actions/list-certificates/20readconfig
- imageroot/pypkg/custom_certificate_manager.py
- imageroot/pypkg/get_certificate.py
Adding custom certificate management inside traeifk module
- added library to handle custom certificate management
- added management of custom certificates for `list-certificates`, `get-certificate` and `delete-certificate`
The actions were modified to allow few to no changes to UI, keeping the behaviour the same.  
UI PR: NethServer/ns8-core#413
> Custom certificate management

- imageroot/update-module.d/11dir_structure
Added migration script that ensures that `custom_certificates` and `configs` folder are present.
Tested:
> Fixing upgrade from 0.0.12

- imageroot/bin/redis2yml
Bug introduced with 8f570c414144cee53d613c1017052060f24c68de. 
The `tls` key does not exists.
> redis2yaml: fix key error

- README.md
- imageroot/actions/get-route/validate-output.json
- imageroot/actions/list-routes/validate-output.json
- imageroot/actions/set-route/20writeconfig
- imageroot/actions/set-route/validate-input.json
- imageroot/pypkg/get_route.py
- tests/10_traefik_routes_api.robot
This pull request adds the `serversTransports` configuration to support self-signed certificate verification. It also adds the `skip_cert_verify` flag to the `get_route` function for handling custom certificates.
we look in services if exists to set to true `skip_cert_verify`  :  `"serversTransport": "backuppc@file"`
```
{
"loadBalancer": {
"servers": [
{
"url": "https://192.168.12.15:443"
}
],
"passHostHeader": true,
"serversTransport": "backuppc@file"
},
"status": "enabled",
"usedBy": [
"backuppc-http@file",
"backuppc-https@file"
],
"serverStatus": {
"https://192.168.12.15:443": "UP"
},
"name": "backuppc@file",
"provider": "file",
"type": "loadbalancer"
},
}
```
if `skipCertVerify` is true then we write to dynamic configuration 
```
http:
services:
backuppc:
loadBalancer:
+ …
```
> Add serversTransports for self-signed certificate verification

- imageroot/actions/set-route/validate-input.json
With webserver we need to create uniq instance name for route, something like `webserver1-www.foo.org`, the PR https://github.com/NethServer/ns8-traefik/pull/50 has introduced a pattern validation to forbid some characters, we need to relax a bit
https://github.com/NethServer/dev/issues/6849
> add dot in set-route validation

- imageroot/actions/set-route/validate-input.json
This pull request adds pattern validation for the virtualhost field in the validate-input.json file. The pattern ensures that the virtualhost is a fully qualified domain name.
https://github.com/NethServer/dev/issues/6853
> Add pattern validation for virtualhost

- imageroot/bin/write-hosts
This fixes a race condition found here: https://community.nethserver.org/t/clean-install-of-ns8-on-debian12-fails-with-redis/23408
Closes https://github.com/NethServer/dev/issues/6912
> fix: retrying with greater backoff to fetch routers list

- imageroot/actions/upload-certificate/21validate_certificates
This pull request adds a new feature to compare the md5 of public keys for certificate validation. Previously, the certificate and key were compared using their md5 hashes, but now we compare the md5 hashes of their public keys instead.
This is needed because we cannot use the modulus with dsa and ec certificates : see https://github.com/NethServer/dev/issues/6937#issuecomment-2137084954
https://github.com/NethServer/dev/issues/6937
> Compare md5 of public keys for certificate validation

- imageroot/actions/delete-certificate/20writeconfig
- imageroot/actions/upload-certificate/21validate_certificates
- imageroot/actions/upload-certificate/23export_certificates
- imageroot/bin/export-certificate
- imageroot/pypkg/custom_certificate_manager.py
- tests/20_traefik_certificates_api.robot
This pull request enhances the management of custom certificates, including improvements to Redis storage and certificate handling logic.
**Key Changes:**
- **Delete Certificate:**
- Improved logic to ensure custom certificates are correctly removed from Redis when requested FQDN is deleted.
- Prevent unnecessary attempts to remove internal certificates when dealing with custom ones.
- **Export Certificate:**
- Added safeguard to avoid overriding custom certificates during the export process.
- **Upload Certificate:**
- Implemented logic to store custom certificates directly in Redis.
- Added validation to check if the uploaded certificate's Common Name (CN) field is missing or empty.
- **Testing:**
- Added and updated tests to verify that custom certificates are correctly handled and …
> Improve Custom Certificate Handling and Redis Storage

- imageroot/actions/upload-certificate/21validate_certificates
To make the validation step more usable from the UI, the following improvements are made:
* Redirect non-JSON error messages to stderr
* Properly signal a validation error to the agent
* Print a properly formatted JSON error message to stdout in case of validation failure
https://github.com/NethServer/dev/issues/6986
> upload-certificate: improve validation step output

- imageroot/actions/upload-certificate/23export_certificates
- tests/20_traefik_certificates_api.robot
This PR addresses several issues related to the handling and storage of custom certificates, ensuring proper functionality and format consistency.
1. **Fix event payload in upload-certificate**  
Adjusted the event payload structure to ensure correct handling of certificate uploads.
2. **Fix certificate format in Redis**  
Ensured certificates are stored in base64 format within Redis for consistency and correct retrieval.
3. **Tests for custom certificate storage**  
Added tests to verify that custom certificates are properly stored in Redis using base64 encoding.
https://github.com/NethServer/dev/issues/6986
> Fix Custom Certificate Handling and Storage in Redis

- imageroot/actions/get-facts/50facts
List the following info:
- number of path-based custom routes
- number of host-bases custom routes
- number of custom/uploaded certificates
- number of acme manual certificates
- number of acme automatic certificates
- number of acme failed certificates
JSON example:
```json
{
"id": "traefik1",
"version": "2.2.5",
"name": "traefik",
"node": "1",
"custom_path_routes": 1,
"custom_host_routes": 1,
"custom_certificates": 1,
"acme_manual_certificates": 2,
"acme_auto_certificates": 1,
"acme_failed_certificates": 1
}
```
See:
- NethServer/ns8-core#784
- NethServer/dev#7274
> feat(phonehome): add get-facts
